### ISSUE TITLE
Hi 👋 What can I do?

### ISSUE THREAD

**Issue by TomWFox** [extinctionrebellion/extinctionrebellion#4]
I'd love to get involved where help is needed/I am able to!

I have experience building iOS apps, some web skills, writing documentation, some python & node.js experience.

If there's something I can do, let me know. I'm happy able to learn new tools etc if that helps.

**Comment by kenorb** [comment]
Join the _Tech_ channel at https://organise.earth/signup_user_complete, then follow the instructions.

**Comment by kenorb** [comment]
Then you can ask for the access to GitLab.
